# Example config for vpnctl

controller:
  listen: "0.0.0.0:8443"
  data_dir: "/var/lib/vpnctl"
  wg_interface: "wg0"
  wg_port: 51820
  mtu: 1280
  direct_mode: "auto" # auto|off
  keepalive_sec: 25
  stun_servers:
    - "stun.l.google.com:19302"
  metrics_path: "/var/lib/vpnctl/metrics.csv"

node:
  name: "modem-a"
  controller: "10.10.10.1:8443"
  wg_interface: "wg0"
  wg_private_key: "<private-key>"
  wg_public_key: "<public-key>"
  vpn_ip: "10.7.0.2/32"
  mtu: 1280
  direct_mode: "auto" # auto|off
  keepalive_sec: 25
  stun_servers:
    - "stun.l.google.com:19302"
  metrics_path: "/var/lib/vpnctl/metrics.csv"
